name: Next.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Use the Node.js version your project requires
        cache: 'pnpm'    # Caches pnpm dependencies

    # Install dependencies using pnpm
    - name: Install dependencies
      run: pnpm install

    # Build the Next.js project
    - name: Build the project
      run: pnpm build

    # Run linting
    - name: Lint the code
      run: pnpm lint

     
