name: Next.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    # Install pnpm
    - name: Install pnpm
      run: npm install -g pnpm

    # Install dependencies using pnpm
    - name: Install dependencies
      run: pnpm install

    # Build the Next.js project
    - name: Build the project
      run: pnpm build

    # Run linting
    - name: Lint the code
      run: pnpm lint

    # Run tests
    - name: Run tests
      run: pnpm test
