name: Linting and Building on Commit
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:

  Continuous-Integration:

    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        run: npm install -g pnpm
        
      - name: Install Dependencies
        run: pnpm install

      - name: Run check linting 
        run: pnpm  lint

      - name: Run production  build 
        run: pnpm  build

      

  