name: Linting and Building on Commit

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  Continuous-Integration:
    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        run: npm install -g pnpm
        
      - name: Install Dependencies
        run: pnpm install

      - name: Run Linting
        run: pnpm lint

      - name: Run Production Build
        run: pnpm build

      - name: Prepare Dockerfile
        run: ./Dockerfile # Note: Ensure this is the correct command; usually, you'd want to build the Docker image instead.

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bargirtufailahmed189/web-app:latest # Corrected tag format

      - name: Verify Pushed Image
        run: docker pull bargirtufailahmed189/web-app:latest